display_name: Quickgui
summary: An elegant virtual machine manager for the desktop
icon: assets/images/logo_pink.png
packager: Martin Wimpress
packagerEmail: code@wimpress.io

vendor: Quickemu Project
requires:
  - zenity
group: Application/Emulator
license: MIT
url: https://github.com/quickemu-project/quickgui

keywords:
  - QEMU
  - quickemu
  - quickget
  - Virtual Machine
  - Hypervisor
  - macOS
  - Windows

categories:
  - System
  - Development

startup_notify: true

# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml
