display_name: Quickgui
package_name: quickgui
generic_name: An elegant virtual machine manager for the desktop
icon: assets/images/logo_pink.png

maintainer:
  name: Martin Wimpress
  email: code@wimpress.io
co_authors:
  - name: Mark Johnson
    email: mark@barrenfrozenwasteland.com
  - name:  Yannick Mauray
    email: yannick.mauray@gmail.com
dependencies:
  - zenity
recommended_dependencies:
  - quickemu
priority: optional
section: x11
installed_size: 16777216
essential: false

keywords:
  - QEMU
  - quickemu
  - quickget
  - Virtual Machine
  - Hypervisor
  - macOS
  - Windows

categories:
  - System
  - Development

startup_notify: true

# You can also specify [metainfo](https://freedesktop.org/software/appstream/docs/chap-Quickstart.html) file
# which contains metadata of the app.
# metainfo: linux/packaging/myappid.appdata.xml
